### ISSUE TITLE
ROS Interface

### ISSUE THREAD

**Issue by bobjohnson2040** [PolySync/oscc#117]
Is there any future plans for a ROS interface? By adding it there would be more compatible open source software and it would encourage more robotics developers to join the OSCC movement!

**Comment by LucasBuckland** [comment]
This is a great idea, thanks for your input! We will add this to our future tasks and I can update you when we end up implementing it.

**Comment by andrewraharjo** [comment]
@bobjohnson2040 you can start leveraging the arduino code with `roslib`

**Comment by bobjohnson2040** [comment]
Any update on this?

**Comment by whitmanjack24** [comment]
+1 
I am also extremely interested in a ROS interface!! 

@LucasBuckland @k-cleary Are either of you panning to implement this?

**Comment by LucasBuckland** [comment]
Hello, yes we are planning on a ROS interface and it is in our road-map. When I have more details I'll follow up on a time-line here. 
Thanks for the feedback!

**Comment by whitmanjack24** [comment]
@LucasBuckland Thank you!

**Comment by rebpdx** [comment]
A ROS node for OSCC is currently in progress. The node will allow for publish and subscribe to ROS messages based on the respective OSCC API types. It is planned to be released in mid October.

**Comment by rebpdx** [comment]
The ROS node is now available, which can be cloned into a catkin workspace. https://github.com/PolySync/roscco
