### ISSUE TITLE
using Other Models of Kia

### ISSUE THREAD

**Issue by antiwong** [PolySync/OSCC#132]
hi,
We are interested in applying these controls to other models of kia. Which models, outside of US, would be suitable for this? Cerato K3 or the Carens?

**Comment by LucasBuckland** [comment]
Hi antiwong, 

Unfortunately we currently don't have support docs for other models of Kia (though technically it still could work as long as the vehicle is similar mechanically to the kia). Having said that, the kia soul is available in most countries as far as we can tell. Is that not the case where you are?
