### ISSUE TITLE
Questions related to wiring and installing the platform

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#141]
I figured it would be easier for people to look at the questions if they were posted as separate issues.

Hi everyone,
I don’t mean to be annoying with so many questions, but honestly I’ve spent quite a bit of time going through the Wiki pages, and there are a lot of things I am confused about related to wiring and installing the platform. I don’t have much of a background assembling wire harnesses or working under the car hood, so more detailed instructions would be greatly appreciated. I bet more people trying to use this platform feel the same way. 
So here are the questions.
1.	How much current (approximately) should be allocated for the entire system (including sensors/future modules)?

2.	As far as power distribution, there seem to be some inconsistencies between the schematic in the Overview page and the one in the Power Distribution page.
Specifically:
-In the “Overview” page, power to the entire system is controlled by both the System Switch and the Emergency stop, whereas in the “Power Distribution” page the CAN gateway and the sensors are independent from the Emergency Stop.
-In the “Overview” page there is a relay and the Fuse Box separating the System Switch from the Emergency stop, whereas in the “Power Distribution” page the two are connected directly.
-In the “Overview” page, there are separate fuses to control how much current can flow to the Brake Module and the other modules, whereas in the “Power Distribution” page all 3 modules receive power from wires branching out of a single relay.
-In the “Overview” page wires of 20 awg gauge are indicated for the +12V and ground connections to the modules, whereas in the “Power Distribution” page 22 awg is indicated.
I can’t think of other inconsistencies at this point, but if you examine the two schematics closely, I’m sure you can find more.
Can you please clarify which schematic should be followed?

3.	From the schematic in the Overview Page

 3a. Are the 200 A fuse and relay closest to the battery already in the car? If not, can you include a link to good parts we can buy online?

3b. How are we supposed to install and connect the System switch, the 200 amp relay and fuse (assuming the latter two are not already in the car) between the battery + terminal and the Fuse Box?

 3c. Are all the fuses and relays in the schematic supposed to go inside the engine compartment? If so, how do we mount them and what tools/parts do we need?

3d. I see the word ‘glovebox’ in parenthesis for the Deutsch connectors. Are the connectors already there? Or is it just a suggestion to put them there along with the modules?

4.	From the schematic in the Power Distribution Page

4a. What are the amp rating requirements for the fuses and relays?

4b. How do we mount the fuses and relays? I know the page says something about using Seaboard. But can you be more specific about the tools/parts/procedure?  

5.	Where are the steering, throttle and gateway modules supposed to go? Inside the glovebox? And how do we run wires from the engine compartment to wherever the modules are supposed to go? Please be specific.

6.	How do you do a proper splice between a wire of a larger gauge, into two or more of a smaller gauge (tools/parts and procedures) ?

7.	How do you access the Break Pedal Switch and the junction and run wires to the OSCC brake module?

8.	Installing the steering and throttle modules requires cutting a pair of wires for each:
   2 wires that connect the torque sensor and EPAS ECU for the steering, and 2 wires that connect the Accelerator Position Sensor and the Throttle Body for the throttle. But what if somebody wants to remove the modules from the car? Would it make sense to terminate the cut wires coming out each sensor and unit with matching plug/receptacle of a Deutsch connector. Or how would you restore the car to its original configuration?

9.	How do you build the Control CAN Bus that will connect the gateway, OSCC modules and the control computer? As I understand, the bus needs to be terminated at both ends with 120 Ω. What connectors/cables/wires/terminators do we need?

10. What about the possibility of installing all the hardware in the back of the car  . Would that be feasible? How should we do the wiring?

**Comment by dan-fern** [comment]
Thank you for your interest in OSCC.  

The OSCC platform does not include any sensors in the system diagram you've referenced.  Any sensor payload that you were to design would require its own power budget to be added upon the base OSCC system.  For reference, however, in-house testing has shown an Alienware Aurora R6 with 2 nVIDIA GTX1070 GPU's running alongside the complete OSCC kit drew a peak load of 200W.  This was captured running on an AC inverter powered off the vehicle battery and stock Kia Alternator (~85A).  

The "Power Distribution" diagram you referenced is outdated and will be replaced when we redesign the wiki next month.  The "Overview" diagram shows the entire system being controlled by the system switch as you mentioned.  It is the more up-to-date system diagram and it contains all the fuse amp ratings and suggested wire gauges.  You should refer to that diagram if you are planning to build a car.

The hardware described in the "Overview" diagram is mostly non-stock.  Many non-OSCC components are off-the-shelf and can be found at popular electronics and mechanical suppliers, with the exception of a few custom mounting brackets and 3D-printed enclosures.  The diagram is listed with suggested locations for 3rd party hardware, but the design is ultimately up to you.  One suggested mounting location is the spare wheel well in the trunk as there is plenty of space to mount hardware and is easy to conceal.  I would also suggest to remove the door trim and run added wiring along stock harnesses.  

The splices into the stock wiring are meant to be permanent.  You could, however, use a different set of Deutsch connectors to reconnect cut wiring and restore the vehicle to it's factory state.  Please reference a Kia parts manual for locations to the brake light switch, torque sensor, EPAS ECU, and Accelerator Position Sensor.  For information about how to splice wires of different gauges, please reference an online tutorial.  The general rule is to add the conductor diameters up for each side and use a splice which fits the summed diameters.

Thank you for raising these points around the complexity of integrating the OSCC kit into a vehicle without much prior knowledge of electrical harnesses or vehicle systems.  In the near future we will announce a complete OSCC “in-a-box” install kit for clients that want a turn-key platform solution.  That option will include all the hardware, components, wiring harnesses, and documentation necessary to build a OSCC vehicle.  For more information you should reach out via email to oscc-orders@polysync.io
