### ISSUE TITLE
The correct schematic for the power distribution

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#143]
As far as power distribution, there seem to be some inconsistencies between the schematic in the Overview page and the one in the Power Distribution page.
Specifically:
-In the “Overview” page, power to the entire system is controlled by both the System Switch and the Emergency stop, whereas in the “Power Distribution” page the CAN gateway and the sensors are independent from the Emergency Stop.
-In the “Overview” page there is a relay and the Fuse Box separating the System Switch from the Emergency stop, whereas in the “Power Distribution” page the two are connected together.
- In the “Overview” page, there are separate fuses to control how much current can flow to the Brake Module and the other modules, whereas in the “Power Distribution” page all 3 modules receive power from wires branching out of a single relay.
- In the “Overview” page wires of 20 awg gauge are indicated for the +12V and ground connections to the modules, whereas in the “Power Distribution” page 22 awg is indicated.
I can’t think of other inconsistencies at this point, but if you examine the two schematics closely, I’m sure you can find more.
Can you please clarify which schematic should be followed?

**Comment by dan-fern** [comment]
Closed per #141
