### ISSUE TITLE
Using the car without the modules after cutting wires from the torque and accelerator sensors.

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#153]
Installing the steering and throttle modules requires cutting a pair of wires for each:
   2 wires that connect the torque sensor and EPAS ECU for the steering, and 2 wires that connect the Accelerator Position Sensor and the Throttle Body for the throttle. But what if somebody wants to remove the modules from the car? Would it make sense to terminate the cut wires coming out each sensor and unit with matching plug/receptacle of a Deutsch connector. Or how would you restore the car to its original configuration?

**Comment by dan-fern** [comment]
Closed per #141
