### ISSUE TITLE
Do we need any connectors for the Control CAN bus?

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#159]
What connector should we use for the Control CAN bus assembly?
 I've read some articles that mention DB9 connector being the industry standard for CAN bus. Other articles mention a 5-pin M12.  Or would using a twisted pair of wires for the CAN-L and CAN-H signals and then Tee-splice each wire individually at each device node work?

**Comment by LucasBuckland** [comment]
Closed as per answer in #163.
