### ISSUE TITLE
Appropriate cable and wires for the Control CAN bus

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#160]
What type of cable and wires do we need ? I'm specifically wondering about wire gauge, cable shield vs unshielded wires, characteristic impedance ( the ISO 11898-2 specifies 120 ohms).
Also does the reference ground also need to be carried in the same cable?
Any recommendations? Links to online parts are always appreciated.

**Comment by LucasBuckland** [comment]
Closed as per answer in #163.
