### ISSUE TITLE
What goes in the fuse box shown in the "Overview" page diagram?

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#161]
It was mentioned in a previous issue that the fuse box shown in the picture refers to an external fuse block that is independent from the fuse box that is in the Kia's engine compartment.  So what exactly is supposed to go inside that fuse block? I mean there are already fuses for all the modules elsewhere in the schematic.

**Comment by LucasBuckland** [comment]
Closed as per answer in #163.
