### ISSUE TITLE
Confused about the amperage of the relays shown in the "Overview" page diagram

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#162]
It was mentioned in a previous issue that the system, with more hardware in addition to the OSCC modules and gateway used about 85 A. But the 2nd relay shown in the "Overview" page diagram (the one that is controlled by the Emergency stop) is rated for 40 A. Is that right? Where is the additional amperage suppose to come from?

**Comment by LucasBuckland** [comment]
This 85 A estimate was including any additional sensors or instrumentation as well as computing power that you may add to the vehicle. 40 A is the correct amperage for the OSCC modules.
