### ISSUE TITLE
Adding a Parts list in the "Overview" page

### ISSUE THREAD

**Issue by ubgit009** [PolySync/OSCC#163]
I know it was mentioned previously that the Wiki is going to updated in the next month., but one thing I think it would be super helpful and would save a lot of time to some people is to have a parts list available . Is there any way, you could PLEASE provide a list of all the parts (with online links when available) needed to implement the diagram from the "Overview page"

**Comment by LucasBuckland** [comment]
Thank you for your questions. I want to start out by saying that this repo is intended as a resource for the general application of the OSCC boards as a research platform. It is not intended to be a detailed installation guide. A certain level of vehicle electrical systems knowledge is necessary to properly install the basic OSCC board kit into a vehicle. For customers that require a turn-key solution, we will soon be offering complete installation kits that will include all the hardware, wiring harnesses, and documentation necessary for a simple and straightforward installation. You won’t even need to splice into the vehicle wiring harness.

As Katie mentioned earlier, a revamp of the wiki is underway that will make the useful boundaries of the repo more clear, with better organization and better labeled diagrams. However, as I’ve mentioned, this is a general-use / reference design resource so it won’t include a fully detailed installation guide. To get you started, I’ve listed some resources below that should give you a good basis of understanding for automotive electrical systems and proper methods of wiring. We’ll be adding these resources (and more) to the redesigned wiki. And, again, we’re going to be announcing a lot more around the OSCC product that will significantly ease installation.

Wiring:
    http://www.onallcylinders.com/2013/12/05/wiring-101-basic-tips-tricks-tools-wiring-vehicle/
CAN Wiring:
    http://www.cowfishstudios.com/blog/canned-pi-part1
Twisted pair:
    https://www.electronics-notes.com/articles/constructional_techniques/hints_and_tips/how-to-make-twisted-pair-wire.php
CAN network overview:
    http://www.ti.com/lit/an/sloa101b/sloa101b.pdf
Soldering technique:
    https://www.sciencebuddies.org/science-fair-projects/project_ideas/Elec_primer-solder.shtml#soldering
Vehicle electrical system basics:
    https://www.howacarworks.com/basics/how-car-electrical-systems-work
Adding a device onto vehicle power circuit
    http://www.instructables.com/id/How-to-Add-a-Circuit-to-Your-Car/
Car Wiring Tips:
    https://www.lifewire.com/diy-car-wiring-tips-534682
