### ISSUE TITLE
Estop STL file

### ISSUE THREAD

**Issue by droter** [PolySync/OSCC#17]
I tried printing the estop stl file on a makerbot mini and it isn't able to print.  

Has anyone tried printing this file?

**Comment by ltbj** [comment]
At what point does the print fail?  

Does the makerbot software generate the gcode from the STL properly?  

Any other info you can provide would be helpful! 

I'm not familiar with the makerbot mini, though it does have a fairly small print bed, only 4 x 5 inches. I'll take another look at the model and check the size.

**Comment by droter** [comment]
It may be a problem with the maker bot.  It fails at the very beginning stalls on 77% after homing.  We are trying the export from solid works again.

There isn't any error messages.  I can test it again.

**Comment by droter** [comment]
Must be something with the makerbot mini and orientation of the part.  We flipped it over so the switch holes were on top and it printed okay.
