### ISSUE TITLE
PID for steering

### ISSUE THREAD

**Issue by DmitryTgn** [PolySync/oscc#187]
Hello, PolySync!
I did not find the steering PID-regulator in the source. Where is the implementation of rotation of the steering wheel at desired angle? Probably it is implemented in PolySync Core?

**Comment by austinjmorlan** [comment]
There is no PID controller for steering in the firmware or the API. Both the API and the firmware are intentionally simplistic: the API passes commands along to the firmware from a higher level application, and the firmware takes those commands and actuates the vehicle. It's the responsibility of a higher level application to perform complex calculations (e.g., a PID controller) and send the necessary commands to the API.
