### ISSUE TITLE
Emergency Stop

### ISSUE THREAD

**Issue by TheMutley** [PolySync/OSCC#19]
Do you have a part number for the EStop button intended for this 3d model ( I didn't found it in the BOM provided) : https://github.com/PolySync/OSCC/tree/devel/3d_models/estop_cupholder

Thanks

**Comment by evanlivingston** [comment]
At PolySync we like to use the [S2ER-E](https://www.autonics.com/products/products_detail.php?catecode=07/03/01&db_uid=174?catecode=07/03/01&db_uid=175?catecode=07/03/01&db_uid=176)3 series emergency stop switch from Autonics.
