### ISSUE TITLE
Broken image links in the wiki

### ISSUE THREAD

**Issue by zwn** [PolySync/OSCC#20]
The wiki contains broken links to images but I was not able to fix them due to:

> You do not have permission to update this wiki.

The links point to https://github.com/PolySync/SelfDrivingSoul instead of https://github.com/PolySync/OSCC.

**Comment by zwn** [comment]
See for example https://github.com/PolySync/OSCC/wiki/Steering but there might be others.

**Comment by evanlivingston** [comment]
@zwn thanks for the heads up. Resolved now. We're still exploring the best route for opening up the wiki to contributions.
