### ISSUE TITLE
Diagramm of tube ports [ PFL PRR PFR PRL PMC1 PMC2 ] for Toyota Prius ABS pump 44510-47050

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc#203]
Diagram of Prius ABS tube port location could help installation and prevent installation errors of brake actuator.

**Comment by rg4444** [comment]
![toyota_prius_abs_pinout](https://user-images.githubusercontent.com/16691942/30989596-e7613d4a-a4a6-11e7-8079-ea565e4e8e73.jpg)
After research this is our educated guess. Pls confirm

**Comment by jweatherson** [comment]
[Brake Line Routing.pdf](https://github.com/PolySync/oscc/files/1345193/Brake.Line.Routing.pdf)

Hi there, I assembled this rough schematic to describe the routing of the brake hoses.  Hope this helps.

James
