### ISSUE TITLE
Brake pump motor doesn't switch off, overheat

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc#205]
Using actuator board 1.2.0 after initialization and pressure creation pump motor doesn't switch off.
Here is the test video: https://www.youtube.com/watch?v=tR9DBHNbcTs No errors seen on serial monitoring port. All property tests passed.
Secondary problem is un-releasing brake pressure after brake control value is set to 0.

**Comment by LucasBuckland** [comment]
Hello, this sounds like you have over-pressured your accumulator. This will cause the pump to keep pumping as the pressure reading is incorrect. Please see issue #131. Which pump power connection are you using? To release the pressure in your accumulator you will need to manually actuate the release valves without the pump pumping.

**Comment by rg4444** [comment]
We use 2 wire sets. In one we use both, in one only BM1. Symptoms are the same.
According this Toyota diagram BM1 and BM2 is simply hard connected inside module.
![prius_abs_power_connections](https://user-images.githubusercontent.com/16691942/31168717-f9dc85c2-a8fe-11e7-900d-1e77552c69e2.JPG)
How "manually actuate without pump" should be done?
How it is possible to check the pressure readings from pump?

**Comment by LucasBuckland** [comment]
BM1 and BM2 are definitely separate from a functional standpoint. Using BM1 significantly increases the longevity of the motor. I'm not sure where that diagram came from but it's different from what I've seen. 
There are a couple utilities that are useful; included in the Brake firmware folder. One is the "release_pressure" utility which should be useful in your situation. I highly recommend caution when using any of the utilities; having a full knowledge of the system and being careful to re-flash normal firmware when you are done is essential.

**Comment by austinjmorlan** [comment]
@rg4444, did @LucasBuckland resolve your issue?

**Comment by rg4444** [comment]
We haven't try yet. Will do after a week and put an update

**Comment by rg4444** [comment]
We are using BM1 (pink) wire. The problem isn't stable. One day pump is switching off, one not with the same joystick driver and firmware. Cause is still unclear.

**Comment by rebpdx** [comment]
@rg4444 Is the oscc git describe you have compiled for joystick commander with the same as the firmware you flashed on to the brake board? When the pump is staying on does it reach and maintain a pressure?

**Comment by rg4444** [comment]
I have narrowed down the cause. Is seams there is pressure inside the system. 
The braking system get back to normal operations when pressure lowering after system standby or Utility firmware "release-brake-pressure" is used.
If you have wrote special pressure release utility - there was a reason for it.
Could you elaborate?
What causing pressure problem and how to resolve it without reflashing Arduino time to time?

**Comment by rg4444** [comment]
Yes - we are testing and have built latest joystick software together with latest OSCC

**Comment by rg4444** [comment]
Started new thread on https://github.com/PolySync/oscc/issues/265
