### ISSUE TITLE
Typo in brake diagramm

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc#207]
There is two 35 pins. One should be 36. The Green one.
![brake_actuator_pinout](https://user-images.githubusercontent.com/16691942/31055916-e882dc3c-a6d2-11e7-8925-da3fd426ff53.png)

**Comment by LucasBuckland** [comment]
Thanks for catching this! We will update.

**Comment by gremme** [comment]
As far as I can tell the incorrect diagram is still up and hasn't been fixed.
