### ISSUE TITLE
Can we buy this hardware?

### ISSUE THREAD

**Issue by yashim** [PolySync/oscc#208]
Hello OSCC team!
Where can we buy this hardware? Or we only can do it by ourself based on the sources from GitHub?

**Comment by k-cleary** [comment]
Hi, @yashim 
We no longer sell the OSCC boards individually, but include them as part of a more complete install system. 
For more information, please check out [drivekit.io](drivekit.io) or shoot us an e-mail at drivekit@polysync.io.

**Comment by yashim** [comment]
Am I right that information provided in this repo is enough to control KIA from computer?

**Comment by yashim** [comment]
Could you please clarify what the difference between drivekit and OSCC board?
