### ISSUE TITLE
Throttle control problem - Unwanted acceleration 

### ISSUE THREAD

**Issue by Akashbaskaran** [PolySync/oscc#222]
For the joystick control of a Kia Soul, A constant voltage(0.36v & 0.72v) is being spoofed onto the blue and green wires (the voltages are values which corresponds to zero acceleration).
An unwanted acceleration is occurring even when the voltages corresponding to zero acceleration is spoofed.
Any idea why this is the case?

**Comment by snewt** [comment]
Hey @Akashbaskaran I've seen this behavior when there is a mismatch between the version of OSCC firmware that was uploaded to the modules and the version joystick commander was built against. I'd check that those versions are identical.
