### ISSUE TITLE
Brake lights remain on if OSCC control is disabled with brakes applied

### ISSUE THREAD

**Issue by jweatherson** [PolySync/oscc#223]
Kia Soul EV- I've found that the brake lights remain on and the brake light switch relay doesn't open if the brakes are applied on the Joystick while simultaneously the disable button is pressed on the Joystick.  Brake pressure is not present in this state.  Only the lights remain on.

**Comment by rebpdx** [comment]
Issue was resolved in PR #248 and included in release [v1.2.0](https://github.com/PolySync/oscc/releases/tag/v1.2.0).
