### ISSUE TITLE
resetting faults

### ISSUE THREAD

**Issue by billtyler** [PolySync/oscc#224]
I see there is a write up on how to reset faults.  What device or software can be used for this?  I have a kvaser leaf, are you aware of software which can do it?  Or are you using some other device?  
I had a hard fault in the steering and had to take it to the dealership to reset it.  Now I have a fault in the throttle module.
thanks

**Comment by snewt** [comment]
Hey @billtyler there are a couple options for resetting faults like those. One that seems to be generally capable is the Launch Creader 8001, another is a higher priced KDS tool kit available through GIT America, Inc.
