### ISSUE TITLE
Board Files BOM

### ISSUE THREAD

**Issue by ahawcker** [PolySync/oscc#227]
In the bill of materials of the boards the column "populate" is empty for some parts. I think that all parts which are not labeled with "dnp" should be populate but i didn't know exactly. Can anybody help?

**Comment by snewt** [comment]
Hey there @ahawcker , are you exporting the BOM from a `.sch` file with eagle? I'd like to be on the same page of the same document.

**Comment by ahawcker** [comment]
Hi, exactly i'm exporting the BOM from the .sch file with eagle. For example the sensor_interface_V1_1_0.sch, what is with the pin strips (Arduino JP) or the connection terminals (Phoenix_4_45)? I think the most of the parts which have no entry at the populate column should populate. Am I right?

**Comment by snewt** [comment]
@ahawcker the BOM associated with each board was not intended to be exported from the schematic so there's no guarantee that what eagle produces from the `.sch` files will be sensical. We recognize that documentation is a valuable resource  and are working on making something available.

**Comment by snewt** [comment]
Hey @ahawcker , a BOM for each board was added to the `devel` branch. For example, the BOM for gateway lives here `https://github.com/PolySync/oscc/tree/devel/hardware/boards/gateway`. They are comma delimited CSV files that can be imported into spreadsheet software like Excel or LibreOffice Calc.
