### ISSUE TITLE
Create style guide.

### ISSUE THREAD

**Issue by galv** [PolySync/OSCC#25]
I noticed a couple of commits that fix style in the repo, for example changing:

```
#define CAN_BAUD (CAN_500KBPS) -> #define CAN_BAUD ( CAN_500KBPS )
```

and 
```
if (foo) {

}
->
if (foo)
{

}
```

It would be super handy for contributors like me to know what the polysync style is so I can follow it from the get-go. Please add it to CONTRIBUTING.md or something like that.

**Comment by galv** [comment]
I also noticed tabs mixed with spaces and dangling whitespace at the end of lines (emacs's whitespace modehighlights these issues for me). You should consider whether you want to require no tabs and to require that whitespace be removed at the end of lines (I think git can be set up via hooks to do this).

**Comment by ltbj** [comment]
We'll get our style guide posted here shortly, thanks for the pointer! FYI we'll enforce spaces only, and no trialling whitespace.

**Comment by evanlivingston** [comment]
@galv We have now added the coding standard! 

https://github.com/PolySync/OSCC/blob/devel/CONTRIBUTING.md
