### ISSUE TITLE
Eagle Library

### ISSUE THREAD

**Issue by TommyBlairesLewis** [PolySync/oscc#295]
This is not an issue, instead a request. Can you guys please update the repo with the EAGLE Library for OSCC?

**Comment by shnewto** [comment]
Hi @TommyBlairesLewis there are EAGLE files associated with each module in their respective hardware directories. The CAN gateway `.sch` and `.brd` files, for example, live here [https://github.com/PolySync/oscc/tree/master/hardware/boards/gateway](https://github.com/PolySync/oscc/tree/master/hardware/boards/gateway)
