### ISSUE TITLE
Gateway Display Connector Part Number

### ISSUE THREAD

**Issue by TommyBlairesLewis** [PolySync/oscc#297]
What is the part number for the CON4/CON8 for the display in the Gateway OSCC Board?

![gateway](https://user-images.githubusercontent.com/22761507/41999210-c63c280a-7a11-11e8-8087-1a66c1dd94f0.JPG)

**Comment by shnewto** [comment]
Hi @TommyBlairesLewis, we don't have a part number. This is an artifact of some work that ultimately wasn't continued for OSCC.
