### ISSUE TITLE
throttle graph in wiki is missing.

### ISSUE THREAD

**Issue by asimay** [PolySync/oscc#299]
### Actual behavior

**throttle graph in wiki is missing.**

### Steps to reproduce

https://github.com/PolySync/oscc/wiki/Hardware-Throttle

![11](https://user-images.githubusercontent.com/8703449/43114191-5e79c16c-8f30-11e8-86ae-2a8e3dd22ae8.PNG)

### Version info
- _What's the output of running `git describe --tags` in your OSCC directory?_
- _Is this the same version flashed onto the hardware?_

**Comment by shnewto** [comment]
Hi @asimay thanks for pointing this out! I've attached included the image here while we work out updating the wiki.
![throttle_stock_diagram](https://user-images.githubusercontent.com/5607902/43159291-ca8025bc-8f36-11e8-83c0-4cf0d0c71926.png)

**Comment by shnewto** [comment]
Image link updated. Thanks again for pointing it out @asimay
