### ISSUE TITLE
Recommended OBDII Tools

### ISSUE THREAD

**Issue by TommyBlairesLewis** [PolySync/oscc#302]
What would you guys recommend for OBDII Tools to clear faults on Niro Hybrid?

**Comment by cotos** [comment]
We recommend using the dealer approved Diagnostic System KDS Kit.

https://kiaspecialtools.com/Catalog/Product/GDSM-CPKITK

This tool will clear faults and provide information about the fault.

You can also get, access to schematics and real time data.
