### ISSUE TITLE
Steering control at 0 MPH

### ISSUE THREAD

**Issue by TommyBlairesLewis** [PolySync/oscc#315]
### Expected behavior

The steering control should be able to turn fully left and right at 0MPH after the ignition

### Actual behavior

The steering is moving but it doesn’t flow full to the right or left 90 degree wise. If the steering gets an extra help, it’d show an error. I guess the release build because DSTEERING was ON.

### Steps to reproduce

Splice only two wires from MOBIS MDPS Kia Niro. White wire is connected to High and Gray color is connected to low. Jumper the SIG A High and SIGB Low to Input and output
Kia C CAN is disconnected, although it should be connected through OBD but I keep getting C CAN is not connected. This particular issue only runs by the steering torque spoof.

### Version info
- _What's the output of running `git describe --tags` in your OSCC directory?_
- _Is this the same version flashed onto the hardware?_ 

Yes, the same with the hardware. Latest release 1.0.0, I assume.

### Hardware info

PolySync original OSCC

We created a quick video for better description

https://youtu.be/ogRkbVM3qvg

**Comment by cotos** [comment]
With 1.0.0 hardware you want to use the 1.0.0 tag
ref:  https://github.com/PolySync/oscc#versions
```
~/oscc$ git describe --tags
v1.0.0
```
You can adjust the steering speed in `oscc-joystick-commander` by doing the following:
```
#define STEERING_RANGE_PERCENTAGE (0.2)  # increase to 4 or 5 to increase steering speed
```
You can increase the steering responsiveness by adjusting the STEERING_RANGE_PERCENTAGE 
We keep it low by default to avoid steering errors.
You may find .36 to be an acceptable value.
ref: https://github.com/PolySync/oscc-joystick-commander/blob/devel/src/commander.c#L31 

When testing steering at 0 MPH you may consider making some turn-tables.

![img_3532](https://user-images.githubusercontent.com/23465569/45566779-837e2200-b80c-11e8-9599-74d28ba279fe.JPG)

Best,
Chris
