### ISSUE TITLE
Brake Module Box

### ISSUE THREAD

**Issue by droter** [PolySync/OSCC#32]
Has anyone found a place to buy a brake module enclosure?

The 3d printed file will cost around $359 on shapeways.  The STC lid and box are around $170.

Is there some other enclosure we can use?
Thanks,

Matt

**Comment by evanlivingston** [comment]
@droter: 

The enclosure for the brake module currently in the repo is for the prototype board.

The new board is significantly smaller. I'm redesigning the enclosure today and doing test prints. The new enclosure should be cheaper to print but I agree an alternative should be found. We will spend some time here looking for project boxes that can accommodate the modules.

Evan

**Comment by droter** [comment]
Would these type of boxes work:
http://www.graybar.com/store/en/gb/non-metallic-junction-box-93172343

**Comment by evanlivingston** [comment]
Those work great. We used those for our prototypes. 

The board to control the brake actuator is 4"x8"x2.5"
