### ISSUE TITLE
The meaning of the P$1 - P$2 Contacts/Pins on Actuator Control Board?

### ISSUE THREAD

**Issue by zxiongunsw** [PolySync/oscc#321]
Hello everyone, we are having difficulty in understanding what the P$1 and P$2 pins/contacts are on the Actuator control board. I have included a snapshot with all the eights pints circled in red. 

<img width="1040" alt="acturtorcontrol_question" src="https://user-images.githubusercontent.com/44182675/46986133-7ae57800-d139-11e8-9581-360371f91378.png">

Could you let me know how those pins are related to the Brake actuator or any other components in OSCC? Thanks a lot!

**Comment by cotos** [comment]
Hi zxiongunsw,

They are mounting holes for the `solenoid banks` heat sinks.
