### ISSUE TITLE
Structures are using bit fields

### ISSUE THREAD

**Issue by petebrink** [PolySync/OSCC#41]
Bit fields are not necessarily safe and can vary according to what processor or compiler is used.  These should be changed to use bit macros (e.g. the Linux versions
#define SET_BIT(p,n) ((p) |= (1 << (n)))
#define CLR_BIT(p,n) ((p) &= (~(1) << (n))) )
to allow for the code to be more specific and safe.

**Comment by petebrink** [comment]
Misplaced the parentheses on the CLR_BIT macro:
#define SET_BIT( bit, index )      ( ( bit ) |= 1 << ( index ) )
#define CLR_BIT( bit, index )      ( ( bit ) &= ~( 1 << ( index ) ) )
#define CHK_BIT( bit, index )      ( ( bit ) & ( 1 << ( index ) ) )

**Comment by LucasBuckland** [comment]
This issue has been resolved in our recent code refactor.
