### ISSUE TITLE
Brake Code Cleanup

### ISSUE THREAD

**Issue by petebrink** [PolySync/OSCC#65]
In general, the brake code is organized correctly, however, there are a variety of libraries used that make it less than portable to another environment, e.g. the map function for converting an input into an overall range and the finite state machine used for a function with two states.

The main purpose of this issue is to go through the code and remove code that is specific to libraries that are only on Arduino.  Either write the implementation in a portable format or isolate and encapsulate the functionality so that it can be easily changed to support a new processor or compiler.

**Comment by LucasBuckland** [comment]
This issue has been resolved in our recent firmware refactor.
