### ISSUE TITLE
Remove doubles from the code

### ISSUE THREAD

**Issue by petebrink** [PolySync/OSCC#66]
The floating point implementation is all done through software emulation.  As a consequence, any floating point operations are limited by the number of times that the processor has to access memory to perform execution on a multi-byte variable.  For doubles, this means that there are at least 8 memory accesses per variable.  The increase in accuracy is of limited benefit as compared to a 'float' operation; all floating point operations should be done with 'float's instead of 'double's.

**Comment by austinjmorlan** [comment]
Resolved with #133.
