### ISSUE TITLE
Include Diagnostic background info in repository

### ISSUE THREAD

**Issue by petebrink** [PolySync/oscc#70]
The Diagnostics for the steering, brake and throttle control have both an explanation and empirical data that are incredibly useful to people using this code.  This issue is specifically around taking that data, converting it to markdown and placing it in the repository.

This should be done for all of the diagnostics that are implemented.

**Comment by LucasBuckland** [comment]
Agreed, we need to add a "data" folder to the Wiki that exposes this information to our users. Will plan for this in the near future.
