### ISSUE TITLE
Steering control should have a timeout for chassis_state_1 frame

### ISSUE THREAD

**Issue by evanlivingston** [PolySync/OSCC#84]
The steering code depends on getting the steering angle from the C-CAN bus via the OBD-II connector. Currently, the firmware does not have a timeout for receiving the CAN frame that contains the steering angle. If the controller does not receive steering angle for any reason (disconnected OBD cable) then the steering controller runs but errantly.

**Comment by petebrink** [comment]
This is going to required that we determine if there is any regularity to this message.  If the message does not get sent when the steering wheel is static, then it is impossible to determine if there has been a timeout.

Recommend doing some empirical testing to determine what the update rate for the chassis message is.

**Comment by joshhartung** [comment]
IIRC they come at a 10ms update rate with very little jitter.

**Comment by LucasBuckland** [comment]
This has been added to our backlog of tasks and will be addressed in the near future.

**Comment by austinjmorlan** [comment]
Resolved with #133.
