### ISSUE TITLE
The brake actuator pinout hasa mislabeled pin

### ISSUE THREAD

**Issue by LucasBuckland** [PolySync/OSCC#92]
In the diagram below there is a mislabelled pin (SLRFL- instead of SLRFR-).

https://github.com/PolySync/OSCC/blob/master/vehicle_info/toyota_prius_xw20/brake/brake_actuator_pinout.png

**Comment by cotos** [comment]
This will be fixed by this PR
https://github.com/PolySync/OSCC/pull/94
